# deploy/vps/04_iis_deploy_vps.ps1
#
# VPS variant of scripts/iis_deploy.ps1 - public, domain-bound, path-agnostic.
# Differs from the local script in three ways:
#   1. GENERATES web.config for THIS machine's path (the committed one hardcodes
#      the dev box's D:\ path, which won't exist here).
#   2. Binds the site to your DOMAIN on port 80 (host header) instead of a bare
#      localhost:8082 - win-acme then adds the 443/HTTPS binding.
#   3. Opens the Windows Firewall for 80 + 443.
# It still creates the AqmarAdmin app pool + grants that pool identity db_owner
# on the aqmar DB, same as local.
#
# Run ELEVATED (Run as administrator). Idempotent - safe to re-run.
#
# Usage:
#   .\deploy\vps\04_iis_deploy_vps.ps1 -Domain admin.yourdomain.com
#   .\deploy\vps\04_iis_deploy_vps.ps1 -Domain admin.yourdomain.com -DbServer localhost -KeepLocalPort

param(
    [Parameter(Mandatory = $true)][string]$Domain,
    [string]$DbServer   = "localhost",
    [string]$DbName     = "aqmar",
    [switch]$KeepLocalPort   # also bind http://localhost:8082 for on-box testing
)

$ErrorActionPreference = "Continue"

# --- elevation guard (relaunch as admin if needed) ---
$isElevated = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()
).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isElevated) {
    Write-Host "Re-launching elevated (UAC prompt)..." -ForegroundColor Yellow
    $reArgs = @(
        "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "`"$PSCommandPath`"",
        "-Domain", $Domain, "-DbServer", $DbServer, "-DbName", $DbName
    )
    if ($KeepLocalPort) { $reArgs += "-KeepLocalPort" }
    Start-Process powershell.exe -Verb RunAs -Wait -ArgumentList $reArgs
    exit
}

$siteName = "AqmarAdmin"
$poolName = "AqmarAdmin"
$sitePath = (Resolve-Path "$PSScriptRoot\..\..").Path
$poolUser = "IIS APPPOOL\$poolName"
$appcmd   = "$env:windir\System32\inetsrv\appcmd.exe"
$venvPy   = Join-Path $sitePath ".venv\Scripts\python.exe"

function Log($m) { Write-Host ("  {0}" -f $m) }
Write-Host "=== AQMAR VPS IIS deploy ===" -ForegroundColor Cyan
Log "Site path: $sitePath"
Log "Domain:    $Domain"
Log "DB:        $DbServer / $DbName"

# --- sanity ---
if (-not (Test-Path "$env:windir\System32\inetsrv\httpPlatformHandler.dll")) {
    Write-Error "HttpPlatformHandler not installed. Install it from iis.net first."; exit 1
}
if (-not (Test-Path $venvPy)) {
    Write-Error "Venv python missing at $venvPy. Create it (README step 5) before deploying."; exit 1
}

# ---------------------------------------------------------------------------
# 1. Generate web.config for THIS machine (absolute paths, guaranteed correct)
# ---------------------------------------------------------------------------
Write-Host "[1/6] Writing web.config for this machine..." -ForegroundColor Cyan
$stdoutLog = Join-Path $sitePath "logs\iis_stdout"
$webConfig = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by deploy/vps/04_iis_deploy_vps.ps1 for this machine's path.
     Do not commit; re-run the deploy script to regenerate. -->
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*"
           modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform
        processPath="$venvPy"
        arguments="-m uvicorn src.admin_app:app --host 127.0.0.1 --port %HTTP_PLATFORM_PORT% --log-level info"
        stdoutLogEnabled="true"
        stdoutLogFile="$stdoutLog"
        startupTimeLimit="60"
        requestTimeout="00:04:00"
        forwardWindowsAuthToken="false">
      <environmentVariables>
        <environmentVariable name="PYTHONIOENCODING" value="utf-8" />
        <environmentVariable name="PYTHONUNBUFFERED" value="1" />
      </environmentVariables>
    </httpPlatform>
  </system.webServer>
</configuration>
"@
Set-Content -Path (Join-Path $sitePath "web.config") -Value $webConfig -Encoding UTF8
Log "web.config -> processPath = $venvPy"

# ---------------------------------------------------------------------------
# 2. App pool (recreate for a clean, known state)
# ---------------------------------------------------------------------------
Write-Host "[2/6] App pool '$poolName'..." -ForegroundColor Cyan
& $appcmd list apppool $poolName *> $null
if ($LASTEXITCODE -eq 0) { & $appcmd delete apppool $poolName *> $null }
& $appcmd add apppool /name:$poolName /managedRuntimeVersion:"" /processModel.identityType:ApplicationPoolIdentity *> $null
& $appcmd set apppool /apppool.name:$poolName /processModel.idleTimeout:00:00:00 *> $null
Log "created (No Managed Code, idle timeout disabled)"

# ---------------------------------------------------------------------------
# 3. Filesystem permissions for the pool identity
# ---------------------------------------------------------------------------
Write-Host "[3/6] Filesystem grants for $poolUser..." -ForegroundColor Cyan
& icacls $sitePath /grant "${poolUser}:(OI)(CI)RX" /T /Q *> $null
if (-not (Test-Path "$sitePath\logs")) { New-Item -ItemType Directory "$sitePath\logs" -Force | Out-Null }
& icacls "$sitePath\logs" /grant "${poolUser}:(OI)(CI)F" /T /Q *> $null
& icacls "$sitePath\data" /grant "${poolUser}:(OI)(CI)F" /T /Q *> $null
Log "RX on repo, F on logs\ + data\"

# ---------------------------------------------------------------------------
# 4. Site + domain binding (+ optional localhost:8082)
# ---------------------------------------------------------------------------
Write-Host "[4/6] Site '$siteName' bound to $Domain :80..." -ForegroundColor Cyan
& $appcmd list site $siteName *> $null
if ($LASTEXITCODE -eq 0) { & $appcmd delete site $siteName *> $null }
& $appcmd add site /name:$siteName /physicalPath:"$sitePath" /bindings:"http/*:80:$Domain" *> $null
& $appcmd set site /site.name:$siteName /[path='/'].applicationPool:$poolName *> $null
if ($KeepLocalPort) {
    & $appcmd set site /site.name:$siteName /+bindings.[protocol='http',bindingInformation='*:8082:'] *> $null
    Log "also bound http://localhost:8082 (on-box testing)"
}
Log "bound http://$Domain (host header)"

# ---------------------------------------------------------------------------
# 5. Firewall for 80 + 443
# ---------------------------------------------------------------------------
Write-Host "[5/6] Firewall rules for 80 + 443..." -ForegroundColor Cyan
foreach ($p in 80, 443) {
    $rule = "AQMAR HTTP $p"
    Get-NetFirewallRule -DisplayName $rule -ErrorAction SilentlyContinue |
        Remove-NetFirewallRule -ErrorAction SilentlyContinue
    New-NetFirewallRule -DisplayName $rule -Direction Inbound -Action Allow `
        -Protocol TCP -LocalPort $p -Profile Any | Out-Null
    Log "allow inbound TCP $p"
}

# ---------------------------------------------------------------------------
# 6. SQL login + db_owner for the app pool identity
# ---------------------------------------------------------------------------
Write-Host "[6/6] SQL grant for $poolUser on [$DbName]..." -ForegroundColor Cyan
$g1 = "USE [master]; IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = '$poolUser') CREATE LOGIN [$poolUser] FROM WINDOWS;"
& sqlcmd -E -S $DbServer -b -Q $g1 *> $null
$g2 = "USE [$DbName]; IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = '$poolUser') CREATE USER [$poolUser] FOR LOGIN [$poolUser]; ALTER ROLE db_owner ADD MEMBER [$poolUser];"
& sqlcmd -E -S $DbServer -d $DbName -b -Q $g2 *> $null
Log "login + db_owner granted"

& iisreset /restart *> $null
& $appcmd start site /site.name:$siteName *> $null

Write-Host ""
Write-Host "IIS deploy done." -ForegroundColor Green
Write-Host "Next: issue the TLS cert with win-acme, then test:" -ForegroundColor Yellow
Write-Host "  C:\path\to\win-acme\wacs.exe    # new cert -> AqmarAdmin site -> http-01"
Write-Host "  Invoke-WebRequest https://$Domain/api/health"

