# deploy/vps/05_setup_tasks_vps.ps1
#
# Registers BOTH AQMAR scheduled tasks on the VPS to run HEADLESS (whether the
# service account is logged on or not), using that account's stored password.
# This is the VPS counterpart to scripts/setup_2hourly_trigger.ps1 +
# setup_nightly_trigger.ps1, which use /it (interactive-only) and stop when you
# log out. It also grants the service account its own SQL login + db_owner,
# because the tasks connect to SQL with Windows auth AS THIS ACCOUNT (the app
# pool's grant from step 6 does not cover it).
#
# The RUN-AS account MUST be the one whose profile holds the git push
# credentials, the claude CLI login, and the .env/session/notify files - so run
# the whole runbook logged in as it. It DEFAULTS to the account you're running
# this script as ($env:USERDOMAIN\$env:USERNAME); pass -RunAsUser only to
# override. S4U ("/np", no stored password) is NOT used on purpose: S4U tasks
# get no network access, and both tasks need the network (Telegram, git, SMTP).
#
# Cadence: hourly scrape on the hour, 00..23 ; nightly verify+publish at 22:15
# (deliberately offset from the scrape slots).
#
# Run ELEVATED. Idempotent - deletes + recreates both tasks and regenerates the
# wrapper scripts (don't hand-edit those).
#
# Usage:
#   .\deploy\vps\05_setup_tasks_vps.ps1            # runs as the current account
#   .\deploy\vps\05_setup_tasks_vps.ps1 -RunAsUser "VPSNAME\otheruser"
#   # prompts for the password; or pass -Password (plain) for automation

param(
    [string]$RunAsUser = "$env:USERDOMAIN\$env:USERNAME",
    [string]$Password,
    [string]$DbServer = "localhost",
    [string]$DbName   = "aqmar"
)

$ErrorActionPreference = "Stop"
$repo   = (Resolve-Path "$PSScriptRoot\..\..").Path
$venvPy = Join-Path $repo ".venv\Scripts\python.exe"
$logDir = Join-Path $repo "logs"
if (-not (Test-Path $venvPy)) { Write-Error "Venv python missing at $venvPy (README step 5)." }
if (-not (Test-Path $logDir)) { New-Item -ItemType Directory $logDir -Force | Out-Null }

Write-Host "Run-as account: $RunAsUser" -ForegroundColor Cyan
Write-Host "  (this account's profile must hold the git creds, claude login, and .env/session files)" -ForegroundColor DarkGray

if (-not $Password) {
    $sec = Read-Host "Password for $RunAsUser" -AsSecureString
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}

# ---------------------------------------------------------------------------
# Wrapper for the hourly scrape (same shape as the local .bat wrapper).
# ---------------------------------------------------------------------------
$scrapeBat = Join-Path $repo "scripts\_run_phase3_silent.bat"
$scrapeLog = Join-Path $logDir "scrape_2hourly.log"
$scrapePy  = Join-Path $repo "scripts\phase3_daily.py"
@"
@echo off
chcp 65001 >nul
set PYTHONIOENCODING=utf-8
cd /d "$repo"
"$venvPy" -W ignore "$scrapePy" >> "$scrapeLog" 2>&1
"@ | Set-Content -Path $scrapeBat -Encoding ASCII

# ---------------------------------------------------------------------------
# Wrapper for the nightly verify+publish. Runs HIDDEN via a .vbs that waits and
# propagates the exit code (so Task Scheduler's Last Run Result reflects a real
# failure - including an SMTP failure, which sends no email). Mirrors the local
# setup_nightly_trigger.ps1 wrapper.
# ---------------------------------------------------------------------------
$nightlyVbs = Join-Path $repo "scripts\_run_nightly_silent.vbs"
$nightlyLog = Join-Path $logDir "nightly_publish.log"
$nightlyPs1 = Join-Path $repo "scripts\nightly_verify_publish.ps1"
@"
' Generated by deploy/vps/05_setup_tasks_vps.ps1 - do not edit (machine paths).
q = Chr(34)
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$repo"
cmd = "cmd /c " & q & q & "powershell.exe" & q & " -NoProfile -ExecutionPolicy Bypass -File " & q & "$nightlyPs1" & q & " >> " & q & "$nightlyLog" & q & " 2>&1" & q
code = sh.Run(cmd, 0, True)
WScript.Quit code
"@ | Set-Content -Path $nightlyVbs -Encoding ASCII

# ---------------------------------------------------------------------------
# Register both tasks with stored credentials.
#   /ru <user> /rp <pass>  = run as this account, whether logged on or not
#   (no /it, no /np). The password is stored encrypted by Task Scheduler.
# schtasks stderr on the pre-delete (task-not-found on first run) is swallowed
# via `cmd /c ... 2>nul` so PS 5.1 doesn't treat it as terminating.
# ---------------------------------------------------------------------------
function Register-AqmarTask($name, $sc, $extra, $tr) {
    & cmd /c "schtasks /delete /tn ""$name"" /f 2>nul" | Out-Null
    $args = @('/create','/tn',$name,'/sc',$sc) + $extra + @(
        '/ru',$RunAsUser,'/rp',$Password,'/rl','LIMITED','/tr',$tr,'/f')
    & schtasks.exe @args
    if ($LASTEXITCODE -ne 0) { Write-Error "schtasks /create failed for '$name' (exit $LASTEXITCODE)." }
    Write-Host "  registered: $name" -ForegroundColor Green
}

Write-Host "Registering scheduled tasks as $RunAsUser (headless)..." -ForegroundColor Cyan

# Hourly scrape: HOURLY /mo 1, first fire 00:00 -> on the hour, 00..23.
# Was /mo 2 until 2026-09-08. The task name keeps "2-Hourly" deliberately —
# it is the identifier the README, BUNDLE-INSTALL.md and the recovery commands
# all use, and renaming it here would register a second task next to the one
# already running rather than replacing it.
Register-AqmarTask "AqmarTofan 2-Hourly Scrape" "HOURLY" @('/mo','1','/st','00:00') `
    ("`"$scrapeBat`"")

# Nightly verify+publish: daily 22:15, hidden via wscript. It starts 15 min
# after a scrape slot and now has ~45 min before the next one (23:00) instead
# of the ~1h45 it had at the 2-hourly cadence. The two are independent — the
# scrape only appends new rows and the nightly reads a snapshot — but if the
# nightly ever grows past ~45 min, move it to :30 rather than shortening it.
Register-AqmarTask "AqmarTofan Nightly Verify+Publish" "DAILY" @('/st','22:15') `
    ("wscript.exe `"$nightlyVbs`"")

# ---------------------------------------------------------------------------
# SQL login + db_owner for the RUN-AS account (tasks use Windows auth as it).
# ---------------------------------------------------------------------------
Write-Host "Granting SQL access to $RunAsUser on [$DbName]..." -ForegroundColor Cyan
$g1 = "USE [master]; IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = '$RunAsUser') CREATE LOGIN [$RunAsUser] FROM WINDOWS;"
& sqlcmd -E -S $DbServer -b -Q $g1 | Out-Null
$g2 = "USE [$DbName]; IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = '$RunAsUser') CREATE USER [$RunAsUser] FOR LOGIN [$RunAsUser]; ALTER ROLE db_owner ADD MEMBER [$RunAsUser];"
& sqlcmd -E -S $DbServer -d $DbName -b -Q $g2 | Out-Null
Write-Host "  login + db_owner granted" -ForegroundColor Green

Write-Host ""
Write-Host "Both tasks registered headless. Verify + smoke-test:" -ForegroundColor Yellow
Write-Host "  schtasks /query /tn ""AqmarTofan 2-Hourly Scrape"" /v /fo LIST | findstr ""Next Run"""
Write-Host "  Start-ScheduledTask -TaskName ""AqmarTofan 2-Hourly Scrape"""
Write-Host "  Get-Content ""$scrapeLog"" -Wait -Tail 30"

