# scripts/setup_nightly_trigger.ps1
#
# Register "AqmarTofan Nightly Verify+Publish": daily 22:30, runs
# scripts\nightly_verify_publish.ps1 HIDDEN (wscript launcher - no console
# window, so nothing can be killed by closing one; the wrapper redirects all
# output to logs\nightly_publish.log via `cmd /c ... >> log 2>&1`).
#
# Same schtasks pattern as setup_2hourly_trigger.ps1: /it (runs while the
# user is logged in - required: claude CLI + git creds live in this user's
# profile), /rl LIMITED, no UAC needed. Re-run any time; it deletes and
# recreates the task and REGENERATES the .vbs (don't hand-edit it).

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path "$PSScriptRoot\..").Path
$taskName = "AqmarTofan Nightly Verify+Publish"
$vbs = Join-Path $repo "scripts\_run_nightly_silent.vbs"
$ps1 = Join-Path $repo "scripts\nightly_verify_publish.ps1"
$logPath = Join-Path $repo "logs\nightly_publish.log"

# The VBS runs powershell HIDDEN (window style 0), WAITS (bWaitOnReturn=True),
# and quits with powershell's exit code so Task Scheduler's Last Run Result
# reflects real failures — including an SMTP send failure, which by definition
# produces no email, making the exit code the only signal. It wraps the call in
# `cmd /c ... >> log 2>&1` so native python/git stdout+stderr are captured to
# the log (a hidden window has no console for Start-Transcript to scrape).
# q = Chr(34) (a double-quote) keeps the nested quoting legible.
$vbsBody = @"
' Generated by setup_nightly_trigger.ps1 - do not edit (machine-specific paths).
q = Chr(34)
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$repo"
cmd = "cmd /c " & q & q & "powershell.exe" & q & " -NoProfile -ExecutionPolicy Bypass -File " & q & "$ps1" & q & " >> " & q & "$logPath" & q & " 2>&1" & q
code = sh.Run(cmd, 0, True)
WScript.Quit code
"@
Set-Content -Path $vbs -Value $vbsBody -Encoding ASCII
Write-Host "Wrote $vbs"

cmd /c "schtasks /delete /tn `"$taskName`" /f 2>nul"
schtasks /create /tn "$taskName" /sc DAILY /st 22:30 /it /rl LIMITED `
    /tr "wscript.exe \`"$vbs\`"" /f
if ($LASTEXITCODE -ne 0) { Write-Error "schtasks /create failed" }

Write-Host "Registered '$taskName' - daily 22:30, hidden."
schtasks /query /tn "$taskName" /v /fo LIST | Select-String -Pattern "Task To Run|Next Run Time|Schedule Type"
